version: '3.7'

services:
  app:
    image: janbinkowski96/accs-app
    build: .
    restart: always
    networks:
      - app_network
    volumes:
      - ./nginx/cert/:/etc/ssl/certs/
      - static_volume:/ACCS/accs_app/staticfiles/
      - media_volume:/ACCS/accs_app/mediafiles/
    depends_on:
      - redis
      - postgres
    env_file:
      .env

  redis:
    image: redis:latest
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - app_network

  flower:
    image: mher/flower
    restart: on-failure
    command: celery --broker=redis://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}/0 flower --basic-auth=${FLOWER_USER}:${FLOWER_PASS} --port=${FLOWER_PORT} --url_prefix=flower
    depends_on:
      - app
      - redis
    networks:
      - app_network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/:/etc/ssl/certs/
      - ./nginx/logs/:/var/log/nginx/
      - static_volume:/ACCS/accs_app/staticfiles/
      - media_volume:/ACCS/accs_app/mediafiles/
    depends_on:
      - app
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
