version: '3.7'

services:
  app:
    build: .
    ports:
    - "8000:8000"
    networks:
      - app_network
    volumes:
      - app_data:/app/files/
      - r_cache:/usr/local/.ExperimentHub/
    depends_on:
      - redis
      - postgres
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  redis:
    image: redis:latest
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASS} --protected-mode yes
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app_network

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  app_data:
  r_cache:
