# Generated by Django 5.1.4 on 2024-12-29 22:31

import django.utils.timezone
import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[models_collection.models.validate_no_slash])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('model_remote_repository', models.CharField(default='', max_length=256, validators=[models_collection.models.validate_url_exists, models_collection.models.validate_github_repo])),
            ],
        ),
    ]
