# Generated by Django 5.0.4 on 2024-05-19 11:11

import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelinstance",
            name="anomaly_detector",
            field=models.FileField(
                max_length=255, upload_to=models_collection.models.ModelInstance.path
            ),
        ),
        migrations.AlterField(
            model_name="modelinstance",
            name="imputer",
            field=models.FileField(
                max_length=255, upload_to=models_collection.models.ModelInstance.path
            ),
        ),
        migrations.AlterField(
            model_name="modelinstance",
            name="model",
            field=models.FileField(
                max_length=255, upload_to=models_collection.models.ModelInstance.path
            ),
        ),
        migrations.AlterField(
            model_name="modelinstance",
            name="scaler",
            field=models.FileField(
                max_length=255, upload_to=models_collection.models.ModelInstance.path
            ),
        ),
    ]
