# Generated by Django 5.1.4 on 2025-01-02 09:43

import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinstance',
            name='metadata',
            field=models.JSONField(default=models_collection.models.ModelInstance.metadata_default),
        ),
    ]
