# Generated by Django 5.0.4 on 2024-05-23 19:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_collection", "0002_alter_modelinstance_anomaly_detector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelinstance",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
