# Generated by Django 5.0.7 on 2024-07-28 11:29

import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_collection", "0003_alter_modelinstance_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelinstance",
            name="preprocessing_flow",
            field=models.FileField(
                default="",
                max_length=255,
                upload_to=models_collection.models.ModelInstance.path,
            ),
        ),
        migrations.AlterField(
            model_name="modelinstance",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
