# Generated by Django 5.0.7 on 2024-11-04 18:01

import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_collection", "0004_modelinstance_preprocessing_flow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelinstance",
            name="preprocessing_flow",
            field=models.FileField(
                max_length=255, upload_to=models_collection.models.ModelInstance.path
            ),
        ),
    ]
