# Generated by Django 5.1.3 on 2024-12-17 17:24

import models_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_collection", "0005_alter_modelinstance_preprocessing_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelinstance",
            name="manifest",
            field=models.FileField(
                default="",
                max_length=255,
                upload_to=models_collection.models.ModelInstance.path,
            ),
            preserve_default=False,
        ),
    ]
