# Generated by Django 5.0.4 on 2024-05-12 08:46

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateField(default=django.utils.timezone.now)),
                ("sample_name", models.CharField(max_length=100)),
                ("diagnosis", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("grn_idat", models.FileField(upload_to=app.models.Sample.path)),
                ("red_idat", models.FileField(upload_to=app.models.Sample.path)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction", models.CharField(max_length=100, null=True)),
                ("confidence", models.FloatField(null=True)),
                ("anomaly", models.BooleanField(null=True)),
                ("anomaly_score", models.FloatField(null=True)),
                ("anomaly_threshold", models.FloatField(null=True)),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.sample",
                    ),
                ),
            ],
        ),
    ]
