# Generated by Django 5.0.4 on 2024-05-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_task_delete_prediction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="sample",
            new_name="sample_id",
        ),
    ]
