# Generated by Django 5.1.4 on 2025-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sample_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='public',
            field=models.BooleanField(default=False, help_text='If public, sample will be accessible by any registered user.'),
        ),
    ]
