# Generated by Django 5.1.4 on 2025-01-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sample_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='public',
            field=models.BooleanField(default=False, help_text='If public, the sample will be accessible to any registered user with the proper link.'),
        ),
    ]
