# Generated by Django 5.0.4 on 2024-05-12 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_sample_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
