# Generated by Django 5.0.4 on 2024-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_sample_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="diagnosis",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_name",
            field=models.CharField(max_length=25),
        ),
    ]
