# Generated by Django 5.0.4 on 2024-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_sample_diagnosis_alter_sample_sample_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="diagnosis",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_name",
            field=models.CharField(max_length=35),
        ),
    ]
