# Generated by Django 5.0.4 on 2024-05-13 10:32

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_sample_grn_idat_alter_sample_red_idat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="grn_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.FileExtensionValidator(["idat"]),
                    django.core.validators.RegexValidator("*_Grn.idat"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="red_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.FileExtensionValidator(["idat"]),
                    django.core.validators.RegexValidator("*_Red.idat"),
                ],
            ),
        ),
    ]
