# Generated by Django 5.0.4 on 2024-05-13 11:08

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_sample_grn_idat_alter_sample_red_idat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="grn_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*_Grn.idat", "Expected file suffix is Grn_idat"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="red_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*_Red.idat", "Expected file suffix is Grn_idat"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
