# Generated by Django 5.0.4 on 2024-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_sample_grn_idat_alter_sample_red_idat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="diagnosis",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_name",
            field=models.CharField(max_length=50),
        ),
    ]
