# Generated by Django 5.0.4 on 2024-07-07 15:05

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_sample_diagnosis_alter_sample_sample_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                ("name", models.SlugField(primary_key=True, serialize=False)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
