# Generated by Django 5.0.7 on 2024-07-28 12:10

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="grn_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*_Grn.idat", "Expected file suffix is _Grn.idat", "iDAT error"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="red_idat",
            field=models.FileField(
                upload_to=app.models.Sample.path,
                validators=[
                    django.core.validators.RegexValidator(
                        ".*_Red.idat", "Expected file suffix is _Red.idat", "iDAT error"
                    )
                ],
            ),
        ),
    ]
