# Generated by Django 5.0.7 on 2024-07-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_sample_grn_idat_alter_sample_red_idat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Documents",
            new_name="Document",
        ),
    ]
