# Generated by Django 5.1.3 on 2024-12-16 10:17

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_documents_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='grn_idat',
            field=models.FileField(upload_to=app.models.Sample.path, validators=[django.core.validators.RegexValidator('.*_Grn.idat*', 'Expected file suffix is _Grn.idat or _Grn.idat.gz', 'iDAT error')]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='red_idat',
            field=models.FileField(upload_to=app.models.Sample.path, validators=[django.core.validators.RegexValidator('.*_Red.idat*', 'Expected file suffix is _Red.idat or _Red.idat.gz', 'iDAT error')]),
        ),
    ]
